#!/usr/bin/env python
import os
import sys

# get title from caller    
titleText = sys.argv[1]
# build output file path    
#opFolder = self.wTree.get_widget("filechooserbutton0").get_filename() 

opFilename = sys.argv[2]

#  outputFilename = opFolder + "/" + opFilename 
outputFilename = opFilename 
# process input files
ipFile1 = sys.argv[3]
if len(sys.argv) > 4:
  ipFile2 = sys.argv[4]
if len(sys.argv) > 5:
  ipFile3 = sys.argv[5]
if len(sys.argv) > 6:
  ipFile4 = sys.argv[6]

# extract (assumed) tune titles from names, and add them to a list 
fileNameList = []
fullPathList = []
# file 1    
try:
  print ("input file 1:" + ipFile1)
  t = os.path.basename(ipFile1)
  s = t.split(".")
  fileNameList.append(s[0])
  fullPathList.append(ipFile1)      
  print ("added " + s[0] + " to list")
except:
  # no file there!
  print ("No file 1!")
# file 2    
try:
  print ("input file 2:" + ipFile2)
  t = os.path.basename(ipFile2)
  s = t.split(".")
  fileNameList.append(s[0])
  fullPathList.append(ipFile2)      
  print ("added " + s[0] + " to list")
except:
  # no file there!
  print ("No file 2!")
# file 3    
try:
  print ("input file 3:" + ipFile3)
  t = os.path.basename(ipFile3)
  s = t.split(".")
  fileNameList.append(s[0])
  fullPathList.append(ipFile3)      
  print ("added " + s[0] + " to list")
except:
  # no file there!
  print ("No file 3!")
# file 4    
try:
  print ("input file 4:" + ipFile4)
  t = os.path.basename(ipFile4)
  s = t.split(".")
  fileNameList.append(s[0])
  fullPathList.append(ipFile4)      
  print ("added " + s[0] + " to list")
except:
  # no file there!
  print ("No file 4!")

# write the output file
print ("opening output file " + outputFilename)
of = open(outputFilename, 'w')


of.write("\\version \"2.24.3\"\n")

# write header comment
of.write("%+-------------------------------------------------------------------------------------+\n")
of.write("%| This file was originally generated by the setmaker2.py python script.               |\n")
of.write("%| If you modify this file and then rerun the script, your modifications will be lost! |\n")
of.write("%+-------------------------------------------------------------------------------------+\n")
of.write("\n")

# header
of.write("\\header { \n" )
of.write("    copyright = \"\"\n" )
of.write("    subtitle = \"  \"\n" )
of.write("    title = \\markup {\n")
of.write("      \\override #'(font-size . 4)\n")
of.write("      \\override #'(font-name . \"URW Palladio L\")\n")
of.write("      \"" + titleText + "\"\n" )
of.write("      }\n" )
of.write("    tagline = \"\"\n" )
of.write("}\n" )

of.write("#(set-global-staff-size 18)\n" )

# paper
of.write("\\paper { \n" )
of.write("    left-margin = 20\n" )
of.write("    right-margin = 20\n" )
of.write("    top-margin = 15\n" )
of.write("    raggedlastbottom = ##t\n" )
of.write("    indent = 0.0\n" )

of.write("    markup-system-spacing =\n")
of.write("      #'((basic-distance . 9)\n")
of.write("         (padding . 0.5)\n")
of.write("         (stretchability . 30)) \n")

of.write("    system-system-spacing =\n")
of.write("      #'((basic-distance . 8)\n")
of.write("         (minimum-distance . 4)\n")
of.write("         (padding . 3)\n")
of.write("         (stretchability . 60)) % defaults: 12, 8, 1, 60\n")

of.write("}\n" )

of.write("\n" )
of.write("% The tune list:\n" )
of.write("\n" )

# include files 
tune_number = 1;
for ipf in fullPathList:
  of.write("% Tune " + str(tune_number) + "\n")
  of.write("%=======\n")
  tune_number = tune_number + 1
  with open(ipf, 'r') as sourceFile:
    for line in sourceFile:
      of.write(line)
  #of.write("\\include \"" + ipf + "\"\n")




# add local copies of the tune variables


# all the tunes in score blocks...
for tunename in fileNameList:
  of.write("\\score {\n")
  of.write("    <<\n")
  of.write("        \\new ChordNames {\n")
  of.write("            %%\\set chordChanges = ##t\n")
  of.write("            \\override ChordName .font-size = #-1\n")
  of.write("            \\" + tunename + "chords\n")
  of.write("        }\n")
  of.write("        \\new Staff \\" + tunename + "melody\n")
  of.write("    >>\n")
  of.write("    \\layout {\n")
  of.write("        \\context {\n")
  of.write("            \\Score\n")
  of.write("            \\remove \"Bar_number_engraver\"\n")
  of.write("            \\override StaffGrouper.staff-staff-spacing.basic-distance = #1\n" )
  of.write("        }\n")
  of.write("    }\n")
  of.write("    \\header {\n")
  of.write("        piece = \\markup { \\fontsize #1 \\" + tunename + "title }\n")
  of.write("        opus = \\markup { \\with-color #(rgb-color 0.4 0.4 0.4) \\fontsize #0.1 \\" + tunename + "notes }\n")
  of.write("    }\n")
  of.write("}\n")
  of.write("\\markup { \\raise #4 \\italic { \\" + tunename + "sourcetext}}\n")


of.close();

# now call lilypond to process the file
lycmd = "lilypond" + outputFilename    
p = os.system("lilypond -ddelete-intermediate-files " + outputFilename)

# delete the lilypond file
#os.remove(outputFilename)

print ("Done!")
print ()
